#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.7.3
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'

require 'strscan'

module Namae
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 117)

  @defaults = {
    :debug => false,
    :prefer_comma_as_separator => false,
    :include_particle_in_family => false,
    :comma => ',',
    :stops => ',;',
    :separator => /\s*(\band\b|\&|;)\s*/i,
    :title => /\s*\b(sir|lord|lady|count(ess)?|(gen|adm|col|maj|capt|cmdr|lt|sgt|cpl|pvt|pastor|pr|reverend|rev|elder|deacon|deaconess|father|fr|rabbi|cantor|vicar|prof|dr|md|ph\.?d)\.?)(\s+|$)/i,
    :suffix => /\s*\b(JR|Jr|jr|SR|Sr|sr|[IVX]{2,})(\.|\b)/,
    :appellation => /\s*\b((mrs?|ms|fr|hr)\.?|miss|herr|frau)(\s+|$)/i,
    :uppercase_particle => /\s*\b(D[aiu]|De[rs]?|St\.?|Saint|La|Les|V[ao]n)(\s+|$)/
  }

  class << self
    attr_reader :defaults

    def instance
      Thread.current[:namae] ||= new
    end
  end

  attr_reader :options, :input

  def initialize(options = {})
    @options = self.class.defaults.merge(options)
  end

  def debug?
    options[:debug] || ENV['DEBUG']
  end

  def separator
    options[:separator]
  end

  def comma
    options[:comma]
  end

  def include_particle_in_family?
    options[:include_particle_in_family]
  end

  def stops
    options[:stops]
  end

  def title
    options[:title]
  end

  def suffix
    options[:suffix]
  end

  def appellation
    options[:appellation]
  end

  def uppercase_particle
    options[:uppercase_particle]
  end

  def prefer_comma_as_separator?
    options[:prefer_comma_as_separator]
  end

  def parse(string)
    parse!(string)
  rescue => e
    warn e.message if debug?
    []
  end

  def parse!(string)
    @input = StringScanner.new(normalize(string))
    reset
    names = do_parse
    names.map(&:merge_particles!) if include_particle_in_family?
    names
  end

  def normalize(string)
    string.scrub.strip
  end

  def reset
    @commas, @words, @initials, @suffices, @yydebug = 0, 0, 0, 0, debug?
    self
  end

  private

  def stack
    @vstack || @racc_vstack || []
  end

  def last_token
    stack[-1]
  end

  def consume_separator
    return next_token if seen_separator?
    @commas, @words, @initials, @suffices = 0, 0, 0, 0
    [:AND, :AND]
  end

  def consume_comma
    @commas += 1
    [:COMMA, :COMMA]
  end

  def consume_word(type, word)
    @words += 1

    case type
    when :UWORD
      @initials += 1 if word =~ /^[[:upper:]]+\b/
    when :SUFFIX
      @suffices += 1
    end

    [type, word]
  end

  def seen_separator?
    !stack.empty? && last_token == :AND
  end

  def suffix?
    !@suffices.zero? || will_see_suffix?
  end

  def will_see_suffix?
    input.rest.strip.split(/\s+/)[0] =~ suffix
  end

  def will_see_initial?
    input.rest.strip.split(/\s+/)[0] =~ /^[[:upper:]]+\b/
  end

  def seen_full_name?
    prefer_comma_as_separator? && @words > 1 &&
      (@initials > 0 || !will_see_initial?) && !will_see_suffix?
  end

  def next_token
    case
    when input.nil?, input.eos?
      nil
    when input.scan(separator)
      consume_separator
    when input.scan(/\s*#{comma}\s*/)
      if @commas.zero? && !seen_full_name? || @commas == 1 && suffix?
        consume_comma
      else
        consume_separator
      end
    when input.scan(/\s+/)
      next_token
    when input.scan(title)
      consume_word(:TITLE, input.matched.strip)
    when input.scan(suffix)
      consume_word(:SUFFIX, input.matched.strip)
    when input.scan(appellation)
      if @words.zero?
        [:APPELLATION, input.matched.strip]
      else
        consume_word(:UWORD, input.matched)
      end
    when input.scan(uppercase_particle)
      consume_word(:UPARTICLE, input.matched.strip)
    when input.scan(/((\\\w+)?\{[^\}]*\})*[[:upper:]][^\s#{stops}]*/)
      consume_word(:UWORD, input.matched)
    when input.scan(/((\\\w+)?\{[^\}]*\})*[[:lower:]][^\s#{stops}]*/)
      consume_word(:LWORD, input.matched)
    when input.scan(/(\\\w+)?\{[^\}]*\}[^\s#{stops}]*/)
      consume_word(:PWORD, input.matched)
    when input.scan(/('[^'\n]+')|("[^"\n]+")/)
      consume_word(:NICK, input.matched[1...-1])
    else
      raise ArgumentError,
        "Failed to parse name #{input.string.inspect}: unmatched data at offset #{input.pos}"
    end
  end

  def on_error(tid, value, stack)
    raise ArgumentError,
      "Failed to parse name: unexpected '#{value}' at #{stack.inspect}"
  end

# -*- racc -*-
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
   -44,    36,    26,    37,   -42,    38,    39,   -44,   -43,   -44,
   -44,   -42,   -41,   -42,   -42,   -43,    51,   -43,   -43,   -41,
    18,   -41,   -41,    74,    60,    59,    61,    75,    16,    13,
    17,   -37,    62,     7,    18,    67,    14,    16,    25,    17,
    16,    25,    17,    28,    67,    14,    46,    70,    14,    36,
    34,    37,    26,    16,    13,    17,    18,    35,     7,    18,
    18,    14,    16,    25,    17,    28,    36,    34,    37,    46,
    14,    36,    34,    37,    35,    36,    34,    37,    46,    35,
    36,    53,    37,    35,   -23,   -23,   -23,    18,    35,    60,
    59,    61,   -23,    36,    34,    37,    46,    62,    36,    34,
    37,    35,    60,    59,    61,    67,    35,   nil,   nil,    46,
    62,    60,    59,    61,    60,    59,    61,   nil,    46,    62,
    19,   nil,    62,    60,    59,    61,   -41,    20,   -25,   nil,
    36,    62,    37,   -41,    36,   nil,    37,    46,   nil,   nil,
   nil,    46 ]

racc_action_check = [
    14,    49,     8,    49,    16,    11,    19,    14,    17,    14,
    14,    16,    25,    16,    16,    17,    31,    17,    17,    25,
    43,    25,    25,    56,    56,    56,    56,    57,     0,     0,
     0,    56,    56,     0,     0,    57,     0,     5,     5,     5,
     9,     9,     9,     9,    45,     5,    47,    50,     9,    10,
    10,    10,    65,    20,    20,    20,    66,    10,    20,    20,
    68,    20,    23,    23,    23,    23,    24,    24,    24,    69,
    23,    28,    28,    28,    24,    29,    29,    29,    72,    28,
    33,    33,    33,    29,    34,    34,    34,    78,    33,    38,
    38,    38,    34,    41,    41,    41,    38,    38,    48,    48,
    48,    41,    51,    51,    51,    80,    48,   nil,   nil,    51,
    51,    70,    70,    70,    75,    75,    75,   nil,    70,    70,
     1,   nil,    75,    81,    81,    81,    13,     1,    13,   nil,
    27,    81,    27,    13,    44,   nil,    44,    27,   nil,   nil,
   nil,    44 ]

racc_action_pointer = [
    25,   120,   nil,   nil,   nil,    34,   nil,   nil,    -7,    37,
    46,     3,   nil,   126,     0,   nil,     4,     8,   nil,     6,
    50,   nil,   nil,    59,    63,    12,   nil,   127,    68,    72,
   nil,    14,   nil,    77,    81,   nil,   nil,   nil,    86,   nil,
   nil,    90,   nil,    11,   131,    34,   nil,    36,    95,    -2,
    45,    99,   nil,   nil,   nil,   nil,    21,    25,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    43,    47,   nil,    51,    59,
   108,   nil,    68,   nil,   nil,   111,   nil,   nil,    78,   nil,
    95,   120,   nil ]

racc_action_default = [
    -1,   -53,    -2,    -4,    -5,   -53,    -8,    -9,   -10,   -26,
   -53,   -53,   -20,   -23,   -24,   -31,   -33,   -34,   -51,   -53,
   -53,    -6,    -7,   -53,   -53,   -23,   -52,   -45,   -53,   -53,
   -32,   -16,   -21,   -26,   -25,   -24,   -33,   -34,   -39,    83,
    -3,   -53,   -16,   -49,   -45,   -46,   -47,   -45,   -53,   -26,
   -15,   -39,   -22,   -23,   -17,   -27,   -40,   -29,   -35,   -41,
   -42,   -43,   -44,   -15,   -11,   -50,   -49,   -48,   -49,   -45,
   -39,   -18,   -53,   -36,   -38,   -53,   -12,   -13,   -49,   -19,
   -28,   -30,   -14 ]

racc_goto_table = [
     3,    43,    30,     1,    22,    21,    81,    72,    32,    27,
    31,   nil,    54,     2,     8,    64,    30,    57,    66,   nil,
     3,    68,    32,    27,    42,    71,    30,    32,    47,    50,
    57,    52,   nil,    40,     8,   nil,   nil,    30,    76,    32,
    77,    63,    30,    78,    79,   nil,    32,     9,    69,    57,
    82,    80,    23,    24,   nil,   nil,    73,    29,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     9,   nil,   nil,
   nil,    41,   nil,   nil,    44,    49,    48,   nil,   nil,   nil,
   nil,    73 ]

racc_goto_check = [
     3,     9,    19,     1,     4,     3,    16,    17,    14,     3,
    11,   nil,    13,     2,     7,    10,    19,    18,     9,   nil,
     3,     9,    14,     3,    11,    13,    19,    14,    11,    11,
    18,    14,   nil,     2,     7,   nil,   nil,    19,    10,    14,
    10,    11,    19,     9,    13,   nil,    14,     8,    11,    18,
    10,    18,     8,    12,   nil,   nil,     3,    12,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     8,   nil,   nil,
   nil,    12,   nil,   nil,     8,     8,    12,   nil,   nil,   nil,
   nil,     3 ]

racc_goto_pointer = [
   nil,     3,    13,     0,    -1,   nil,   nil,    14,    47,   -26,
   -28,     0,    48,   -26,    -2,   nil,   -69,   -49,   -21,    -7 ]

racc_goto_default = [
   nil,   nil,   nil,    58,     4,     5,     6,    65,    33,   nil,
   nil,    11,    10,   nil,    12,    55,    56,   nil,    45,    15 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 13, :_reduce_1,
  1, 13, :_reduce_2,
  3, 13, :_reduce_3,
  1, 14, :_reduce_4,
  1, 14, :_reduce_none,
  2, 14, :_reduce_6,
  2, 14, :_reduce_7,
  1, 14, :_reduce_none,
  1, 17, :_reduce_9,
  1, 17, :_reduce_10,
  4, 16, :_reduce_11,
  5, 16, :_reduce_12,
  5, 16, :_reduce_13,
  6, 16, :_reduce_14,
  3, 16, :_reduce_15,
  2, 16, :_reduce_16,
  3, 18, :_reduce_17,
  4, 18, :_reduce_18,
  5, 18, :_reduce_19,
  1, 24, :_reduce_none,
  2, 24, :_reduce_21,
  3, 24, :_reduce_22,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 25, :_reduce_27,
  3, 25, :_reduce_28,
  1, 25, :_reduce_29,
  3, 25, :_reduce_30,
  1, 20, :_reduce_none,
  2, 20, :_reduce_32,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 28, :_reduce_none,
  2, 28, :_reduce_36,
  0, 29, :_reduce_none,
  1, 29, :_reduce_none,
  0, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  0, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 30, :_reduce_none,
  2, 30, :_reduce_48,
  0, 22, :_reduce_none,
  1, 22, :_reduce_none,
  1, 19, :_reduce_none,
  2, 19, :_reduce_52 ]

racc_reduce_n = 53

racc_shift_n = 83

racc_token_table = {
  false => 0,
  :error => 1,
  :COMMA => 2,
  :UWORD => 3,
  :LWORD => 4,
  :PWORD => 5,
  :NICK => 6,
  :AND => 7,
  :APPELLATION => 8,
  :TITLE => 9,
  :SUFFIX => 10,
  :UPARTICLE => 11 }

racc_nt_base = 12

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "COMMA",
  "UWORD",
  "LWORD",
  "PWORD",
  "NICK",
  "AND",
  "APPELLATION",
  "TITLE",
  "SUFFIX",
  "UPARTICLE",
  "$start",
  "names",
  "name",
  "word",
  "display_order",
  "honorific",
  "sort_order",
  "titles",
  "u_words",
  "opt_suffices",
  "opt_titles",
  "last",
  "von",
  "first",
  "particle",
  "opt_words",
  "words",
  "opt_comma",
  "suffices",
  "u_word" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 11)
  def _reduce_1(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 12)
  def _reduce_2(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 13)
  def _reduce_3(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 15)
  def _reduce_4(val, _values, result)
     result = Name.new(:given => val[0])
    result
  end
.,.,

# reduce 5 omitted

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_6(val, _values, result)
     result = val[0].merge(:family => val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_7(val, _values, result)
     result = val[1].merge(val[0])
    result
  end
.,.,

# reduce 8 omitted

module_eval(<<'.,.,', 'parser.y', 21)
  def _reduce_9(val, _values, result)
     result = Name.new(:appellation => val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 22)
  def _reduce_10(val, _values, result)
     result = Name.new(:title => val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_11(val, _values, result)
             result = Name.new(
           :given => val[0], :family => val[1], :suffix => val[2], :title => val[3]
         )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_12(val, _values, result)
             result = Name.new(
           :given => val[0..1].join(' '), :family => val[2], :suffix => val[3], :title => val[4]
         )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 38)
  def _reduce_13(val, _values, result)
             result = Name.new(
           :given => val[0], :nick => val[1], :family => val[2], :suffix => val[3], :title => val[4]
         )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 44)
  def _reduce_14(val, _values, result)
             result = Name.new(
           :given => val[0], :nick => val[1], :particle => val[2], :family => val[3], :suffix => val[4], :title => val[5])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_15(val, _values, result)
             result = Name.new(:given => val[0], :particle => val[1], :family => val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_16(val, _values, result)
             result = Name.new(:particle => val[0], :family => val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 58)
  def _reduce_17(val, _values, result)
             result = Name.new({
           :family => val[0], :suffix => val[2][0], :given => val[2][1]
         }, !!val[2][0])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_18(val, _values, result)
             result = Name.new({
           :particle => val[0], :family => val[1], :suffix => val[3][0], :given => val[3][1]
         }, !!val[3][0])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 70)
  def _reduce_19(val, _values, result)
             result = Name.new({
           :particle => val[0,2].join(' '), :family => val[2], :suffix => val[4][0], :given => val[4][1]
         }, !!val[4][0])

    result
  end
.,.,

# reduce 20 omitted

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_21(val, _values, result)
     result = val.join(' ')
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 78)
  def _reduce_22(val, _values, result)
     result = val.join(' ')
    result
  end
.,.,

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_27(val, _values, result)
     result = [nil,val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_28(val, _values, result)
     result = [val[2],val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 86)
  def _reduce_29(val, _values, result)
     result = [val[0],nil]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 87)
  def _reduce_30(val, _values, result)
     result = [val[0],val[2]]
    result
  end
.,.,

# reduce 31 omitted

module_eval(<<'.,.,', 'parser.y', 90)
  def _reduce_32(val, _values, result)
     result = val.join(' ')
    result
  end
.,.,

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

module_eval(<<'.,.,', 'parser.y', 95)
  def _reduce_36(val, _values, result)
     result = val.join(' ')
    result
  end
.,.,

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

module_eval(<<'.,.,', 'parser.y', 105)
  def _reduce_48(val, _values, result)
     result = val.join(' ')
    result
  end
.,.,

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

module_eval(<<'.,.,', 'parser.y', 110)
  def _reduce_52(val, _values, result)
     result = val.join(' ')
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Namae
